### ISSUE TITLE
Can't load assets/ because the admin UI needs that path.

### ISSUE THREAD

**Issue by clahey** [ArisiaInc/a21-remote-site#131]

**Comment by clahey** [comment]
We could change angular to use fassets/ or frontend-assets/. I haven't decided which I prefer.

Or frontend/assets/.

Alternatively, maybe we could change scala to use admin/assets for more consistency? Not sure how much work it is to change that in scala.

The work in angular is fairly trivial. (I have a working patch)

**Comment by jducoeur** [comment]
This got fixed on the backend side.
