### ISSUE TITLE
Throw open the doors

### ISSUE THREAD

**Issue by jducoeur** [ArisiaInc/a21-remote-site#132]
Somewhere late in the game (likely final week, although which day is uncertain), remove the restriction that only Admins and Early Access users can get into the site.  This is controlled by the config flag `arisia.early.access.only` -- turning that to `false` will open the door to everyone.

**Comment by Gailbear** [comment]
we need to remember to loop reg in on the "when" decision, and also helpdesk. this was something conzealand forgot and it sucked.

**Comment by jducoeur** [comment]
I think Reg largely has final say on this: I don't want to do it until they are prepared to deal with People.  I talked with Melia about this a little bit some time back (a month or two ago), but I don't think she yet knows what she wants in terms of timing.
