### ISSUE TITLE
Backend support for ducks

### ISSUE THREAD

**Issue by jducoeur** [ArisiaInc/a21-remote-site#152]
This needs a schema, and lots of design.

**Comment by jducoeur** [comment]
Assigning to Gail to fill in details of the needed endpoints and schema.

**Comment by jducoeur** [comment]
Possibly belongs in a general "user meta" table, along with preferences?

**Comment by Gailbear** [comment]
```
ducks {
  id: whatever primary key (int or string);
  image: string/uri;
  alt: string; // alt text describing the image
  link: string; // this is the url it goes to, preferably starting with the slash after the domain
  hint: string; // this is the alt text on the shadow if you haven't found it yet
  requesting_url: string/uri; // the uri the request needs to come from to be valid
}
```

```
GET /api/ducks/ -- list of duck objects (all of them)
GET /api/ducks/id -- duck object with that id
POST /api/ducks/id -- NO PAYLOAD -- assign signed in user the duck with that id, if the request comes from the right requesting_url
```

admin portal: basic CRUD ducks - image upload to s3? also some ability to link ducks to users

other requirements: /api/user/id should return a list of duck ids

**Comment by Gailbear** [comment]
alternatively we can also do all the duck imaging on the front end - might be easier.

**Comment by jducoeur** [comment]
Got this mostly done a couple of days ago.  Still needs the UD in CRUD, but good enough to get started.
