### ISSUE TITLE
decide on link scheme for automated zooms

### ISSUE THREAD

**Issue by Gailbear** [ArisiaInc/a21-remote-site#171]
proposal:
/panel/xxx/zoom => checks to see if you are logged in and rectifies if not, 302 to /api/panel/xxx/zoom, which 302 to actual zoom link

/panel/xxx brings you to /schedule/panel/xxx if it's not now or imminent, or /program/room_whatever or /events or /gaming if it's now or imminent

**Comment by jducoeur** [comment]
> /panel/xxx/zoom => checks to see if you are logged in and rectifies if not, 302 to /api/panel/xxx/zoom, which 302 to actual zoom link

I'm going to follow this suggestion, but with the addition that there will be a `zoomhost` variant of both of these URLs, available only for potential Zoom hosts, which redirects to the Zoom Host link instead of the attendee one.

**Comment by jducoeur** [comment]
Actually, tweaking that: let's make it `/api/schedule/xxx/zoom` -- that's more consistent with the rest of the API, and avoids confusion about panels vs events vs whatever.
