### ISSUE TITLE
starred items for schedule

### ISSUE THREAD

**Issue by Gailbear** [ArisiaInc/a21-remote-site#177]
can 'star' and 'unstar' and item on the schedule (see figma for placement)

hollow star icon for no star, solid for star?

saved on the user. api endpoints should be

`GET /api/starred` to get starred items for logged in user
`POST /api/starred/id` to star that program item

starred should be attached to the user on the frontend - possibly should also come with /me or whatever i called that endpoint

in addition, there should be a 'my schedule' tab (like where program and people are) that lists all the things you've starred.

**Comment by jducoeur** [comment]
Talked about this in Slack, but for the record -- this is already fully implemented on the backend side, with endpoints:
```
# Fetch the stars for the current user; returns a JSON list of program IDs
GET     /api/schedule/stars          arisia.controllers.ScheduleController.getStars()
# Add a star from the specified program item ID
PUT     /api/schedule/stars/:which   arisia.controllers.ScheduleController.addStar(which)
# Remove the star for the specified program item ID
DELETE  /api/schedule/stars/:which   arisia.controllers.ScheduleController.removeStar(which)
```
Give a yell if you need these changed.

**Comment by jducoeur** [comment]
Seemed to be completely working at the con.
