### ISSUE TITLE
add ballot link to art show page

### ISSUE THREAD

**Issue by Raven-St** [ArisiaInc/a21-remote-site#260]
In the tours and artist chat box at the top of the art show page, we also need to add a ballot form: https://docs.google.com/forms/d/1bKIrWquuPKYR1vMeUMPpzhmINk0Ro1Bilteh0L_N9nQ/edit?usp=sharing

This can go at the bottom off the box under the heading "Vote on the Popular Choice Award"

**Comment by emtersoff** [comment]
Done!
