### ISSUE TITLE
I should be able to get to program items directly from the schedule

### ISSUE THREAD

**Issue by jducoeur** [ArisiaInc/a21-remote-site#27]
This is just a story, but a pretty foundational one with a lot of implications.

The underlying theory here (and mind, this needs UX eyes on it) is that we will have at least one, possibly multiple, views of the Arisia schedule, which participants will be using actively.  We always have that -- traditionally it's been implemented in Konopas and/or Guidebook.

But for this year, it seems like we have an additional and important constraint: the schedule is part of the member's workflow as they navigate the convention, and we want that navigation to be as easy as possible.

That seems to lead directly to the conclusion that, if I'm looking at the schedule for a current or upcoming program item, it should link right to that event -- with a reasonable minimum of clicks, I should be able to go directly into that item.  In particular, I shouldn't have to go navigate around to find it.

The reason this is important is that it seems to carry a corollary that we are probably building our own schedule system.  That's a pain in the tuchus, but I'm not sure that it is avoidable.

**Comment by Raven-St** [comment]
I've seen this done several ways that work - from a fully-interactive and searchable scheduling site to a linked PDF of the schedule. I couldn't find documentation for Konopas that mentioned linking, but Guidebook [explicitly supports](https://support.guidebook.com/hc/en-us/articles/360053222113-Link-video-and-live-streams-to-enhance-your-virtual-event) linking video meetings/presentations to the schedule in the app.

We may still want to build our own system, but it might be possible to use Guidebook and a linked PDF version to provide a similar experience to what attendees would have in the hotel.

**Comment by jducoeur** [comment]
Nchanter pointed out (in a Slack thread) that [Konopas is completely open source](https://github.com/eemeli/konopas), under a super-permissive license, and we already integrate it with Zambia.  And it's *my* favorite schedule app anyway: not perfect, but generally easy to use, and usable on both browser and mobile.

(Really, its only downside is that it has no concept of identity: when you mark items that you want to do, they are only remembered in the local browser, not on the server.  But that's probably less of an issue for this particular convention than for the in-person one, since I suspect fewer people will be scheduling on their laptop and then attending on their phone this year.)

So it's quite possible that the right answer is for us to just intercept the data on the way from Zambia to Konopas, enrich it with the links to the pages for each program item, and we're done.  That would be pleasantly straightforward if it pans out.

**Comment by Raven-St** [comment]
That would work! Keeping within a scheduling tool attendees are familiar with is valuable I think, especially given how new/different the rest of the workflow will be for folks.
