### ISSUE TITLE
I should be able to show off my cosplay, and hang out with other cosplayers

### ISSUE THREAD

**Issue by jducoeur** [ArisiaInc/a21-remote-site#30]
This is a hand-wave of a story for now -- a reminder that we should think about this area, looking for user research and brainstorming.

Cosplay is an important aspect of Arisia: the Masquerade aside, huge numbers of people costume for it, and enjoy attending very conspicuously in costume.

What is the online equivalent?  How do folks *do* cosplay in a serious way in the online environment?

**Comment by Raven-St** [comment]
We can (and should) do some research here, but I am a costumer and have attended a virtual costuming con during quarantine. I can share some of what I've seen work well and also what the community typically uses to share.

**Comment by jducoeur** [comment]
That would be great -- I'm totally not a costumer, and not part of that community, so I have only a vague idea of what might be appropriate.

**Comment by jducoeur** [comment]
This is in the design as the Coffee Shop Line in the Lobby.
