### ISSUE TITLE
Handle Discord rate limiting

### ISSUE THREAD

**Issue by jducoeur** [ArisiaInc/a21-remote-site#389]
To my mild dismay, I've already seen rate-limit errors from Discord.  So we're going to have to handle these in the server, and slow things down.

**Comment by Gailbear** [comment]
hahahahahahahahaha

**Comment by jducoeur** [comment]
Specifically, I've gotten:
```
2021-01-14 15:46:24 ERROR arisia.discord.DiscordServiceImpl  Got unexpected response from Discord getMember:
{
  "global": false, 
  "message": "You are being rate limited.", 
  "retry_after": 8243
}
```

Details on the subject: https://discord.com/developers/docs/topics/rate-limits#rate-limits
