### ISSUE TITLE
Choose the front end architecture

### ISSUE THREAD

**Issue by jducoeur** [ArisiaInc/a21-remote-site#4]
Spinning out of a conversation on Slack with @Gailbear -- there are two broad approaches that we could use for the front end of this thing:

* SPA -- we build a single-page front end using Angular or React or something like that.  "Pages" are code, calling the back end API.
* "Classic" MVC -- pages are defined as Twirl templates.

Or possibly something in-between, even, with an SPA constructed from components.

The SPA approach is generally more modern and powerful, but requires more technical nous for constructing the front end.

We'll need to decide this soon, before we start seriously coding anything, since it affects the entire front half of the application.

**Comment by jducoeur** [comment]
Ideally, we'd like this to cope with a websocket connection, so that we could have, eg, live Discord chat via a 'bot.

**Comment by Gailbear** [comment]
we're trying angular! (not angularjs, they are different) so we'll see how that goes.
