### ISSUE TITLE
There should be a secure private channel for IRT to work together

### ISSUE THREAD

**Issue by jducoeur** [ArisiaInc/a21-remote-site#44]
From Raven's notes:

> A private, secure (password-protected? linked to certain accounts?) space for IRT staff to chat/coordinate as needed, if they don't already have a platform they are comfortable with

The most obvious idea here is a locked Discord channel, but we should see whether IRT has their own preferences, and we should confirm that it is actually possible to get an appropriate level of security for a locked channel.

**Comment by Raven-St** [comment]
Related: there should be locked/limited access channels for other "private" space socializing/communicating (e.g. Staff Den, Green Room, Masquerade Green Room). Should I make a new/separate issue for this?

**Comment by jducoeur** [comment]
Yeah, please do -- while the concepts are related, it wouldn't surprise me if the details vary.  In particular, the IRT space needs to be much more secure than the Green Room does, and that might affect how we manage it.
