### ISSUE TITLE
Add table of Hannibal commission hours to his Art Show page

### ISSUE THREAD

**Issue by Raven-St** [ArisiaInc/a21-remote-site#452]
Saturday | 2:30 - 5:30 PM | Art Show Breakout Room | Commission Table
Sunday | 8:30 - 10:30 PM | Art Show Breakout Room | Commission Table
Sunday | 1 - 2:45 PM | Art Show Breakout Room | Commission Table
Sunday | 3:45 - 5:30 PM | Art Show Breakout Room | Commission Table
Sunday | 8:30 - 10:30 PM | Art Show Breakout Room | Commission Table
Monday | 10 AM - 12 PM | Art Show Breakout Room | Commission Table

**Comment by jducoeur** [comment]
Don't know whether this happened or not, but if not, it isn't going to -- it's really not a v2 thing.
