### ISSUE TITLE
Make Zoom links in Schedule clickable so they go to Zoom meeting

### ISSUE THREAD

**Issue by dhsysgithub** [ArisiaInc/a21-remote-site#459]
After Justin's fix to not duplicate Zoom meetings, clicking on the Zoom link in the schedule item for the Zoom meeting makes zoom still ask for the password.   The password is not being recognized by Zoom as a parameter on the link href.

Also it's not possible to just click on the Zoom link, because the UI thinks it's a mouse click to collapse the expanded Schedule item.

**Comment by jducoeur** [comment]
This really wasn't a Zoom-related bug -- it's that the HTMLifier doesn't recognize query params yet.  And it's kind of a non-issue: that was only happening to the emergency-improv links on Friday night, not the real system.
