### ISSUE TITLE
Costume Feed

### ISSUE THREAD

**Issue by Gailbear** [ArisiaInc/a21-remote-site#99]
carousel of photos; in "normal" design mode, rotate photos every 20 seconds. users can click the photo to enlarge, and click arrows on either side to advance manually. In "plain" mode, photos do not automatically advance. If user hovers over a photo, show caption.

**Comment by clahey** [comment]
I was confused when I read this because I didn't realize there was a "plain" mode.

**Comment by clahey** [comment]
I'm gonna use fake data for now. Where are the images going to come from? Are people going to be able to post new photos during the con?

**Comment by jducoeur** [comment]
Photos are going to be collected and vetted by Member Services, mainly pre-con.  Being able to add more during the con is a Nice to Have, not critical.

Precisely where the photos live is TBD, as far as I know.  I *suspect* we'll put them in an S3 bucket and randomize them from there, but we really haven't talked it through.

**Comment by clahey** [comment]
UI is implemented. Design may give feedback. Doesn't load images from the backend. (Just uses the same images as used in the Angular Bootstrap examples.)

**Comment by jducoeur** [comment]
This is live on the site, and seems to be working well.
